variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-basic-linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMME'
    subscriptionId: '750dfa4a-44bb-4efc-b27a-aea57495cde1' #Change for yours
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipelinesDAVE-rg'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-webAppName az400123456'
    #-administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'
